apiVersion: v1
kind: Service
metadata:
  name: {{ include "frps.fullname" . }}
  labels:
    {{- include "frps.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: bind
      protocol: TCP
      name: http
  selector:
    {{- include "frps.selectorLabels" . | nindent 4 }}
